name: CI test and publish Docker image

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev
      
defaults:
  run:
    working-directory: ./appliance/alpine
        
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Run Build script
        run: ./build.sh

  publish:
    name: Publish to Docker Hub
    needs: test
    runs-on: ubuntu-latest
    if: (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev') && github.repository_owner == 'mattster98'
    env:
      DOCKER_IMAGE: mattster98/rsyslog-docker
      PLATFORMS: linux/amd64,linux/arm64
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Clean git Checkout
        if: success()
        uses: actions/checkout@v2
      - name: Build, tag and push the dev Docker image
        if: success() && github.ref == 'refs/heads/dev'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          no-cache: true
          platforms: ${{ env.PLATFORMS }}
          tags: |
            ${{ env.DOCKER_IMAGE }}:dev_${{ github.sha }}
            ${{ env.DOCKER_IMAGE }}:latest_dev

      - name: Build, tag and push the master Docker image
        if: success() && github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          no-cache: true
          platforms: ${{ env.PLATFORMS }}
          tags: |
            ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
            ${{ env.DOCKER_IMAGE }}:latest
